# Generated by Django 6.0.2 on 2026-02-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='lead',
            name='interest',
            field=models.CharField(choices=[('member', 'Join as member'), ('volunteer', 'Volunteer'), ('partner', 'Partner'), ('other', 'Other')], default='member', max_length=20),
        ),
    ]
