# Generated by Django 6.0.2 on 2026-02-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_full_name_alter_lead_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_newcomer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='wants_event_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='wants_launch_updates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='wants_sunday_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='wants_to_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='wants_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
